## Import Libraries

In [17]:
import os
import h5py
import numpy as np
import pandas as pd
from pandas import DataFrame
#import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

## Loading Data

In [18]:
# Load data
filename = 'N-CMAPSS_DS02.h5'
with h5py.File(filename, 'r') as hdf:
            # Development set
            W_dev = np.array(hdf.get('W_dev'))             # W
            X_s_dev = np.array(hdf.get('X_s_dev'))         # X_s
            #X_v_dev = np.array(hdf.get('X_v_dev'))         # X_v
            #T_dev = np.array(hdf.get('T_dev'))             # T
            Y_dev = np.array(hdf.get('Y_dev'))             # RUL  
            A_dev = np.array(hdf.get('A_dev'))             # Auxiliary
            
            # Test set
            W_test = np.array(hdf.get('W_test'))           # W
            X_s_test = np.array(hdf.get('X_s_test'))       # X_s
            #X_v_test = np.array(hdf.get('X_v_test'))       # X_v
            #T_test = np.array(hdf.get('T_test'))           # T
            Y_test = np.array(hdf.get('Y_test'))           # RUL  
            A_test = np.array(hdf.get('A_test'))           # Auxiliary
            
            # Varnams
            W_var = np.array(hdf.get('W_var'))
            X_s_var = np.array(hdf.get('X_s_var'))  
            #X_v_var = np.array(hdf.get('X_v_var')) 
            #T_var = np.array(hdf.get('T_var'))
            A_var = np.array(hdf.get('A_var'))
            
            # from np.array to list dtype U4/U5
            W_var = list(np.array(W_var, dtype='U20'))
            X_s_var = list(np.array(X_s_var, dtype='U20'))  
            #X_v_var = list(np.array(X_v_var, dtype='U20')) 
            #T_var = list(np.array(T_var, dtype='U20'))
            A_var = list(np.array(A_var, dtype='U20'))

In [19]:
# Concat all development data
Dev = np.concatenate((W_dev, X_s_dev, A_dev, Y_dev), axis=1)

# Concat all test data
Test = np.concatenate((W_test, X_s_test, A_test, Y_test), axis=1)

In [20]:
print(X_s_dev.shape)

df_Dev_cols = ['alt', 'Mach', 'TRA', 'T2', 'T24', 'T30', 'T48', 'T50', 'P15', 'P2', 'P21', 'P24',
 'Ps30', 'P40', 'P50', 'Nf', 'Nc', 'Wf', 'unit', 'cycle', 'Fc', 'hs', 'RUL']

#df_Dev_cols = ['alt', 'Mach', 'TRA', 'T2', 'Wf', 'Nf', 'Nc', 'T24', 'T30', 'T48', 'T50', 'P15', 'P2', 'P21', 'P24', 'Ps30', 'P40', 'P50', 'unit', 'cycle', 'Fc', 'hs','RUL']

df_Dev = pd.DataFrame(Dev,columns=df_Dev_cols)
df_Test = pd.DataFrame(Test,columns=df_Dev_cols)

display(df_Dev)
display(df_Test)

(5263447, 14)

,alt,Mach,TRA,T2,T24,T30,T48,T50,P15,P2,...,P40,P50,Nf,Nc,Wf,unit,cycle,Fc,hs,RUL
0,10005.0,0.448497,76.903748,502.420918,600.148034,1438.498187,1818.027714,1228.129848,15.806267,11.577097,...,336.631827,12.629361,2160.926416,8591.373490,3.855337,2.0,1.0,3.0,1.0,74.0
1,10013.0,0.447741,76.903748,502.326114,600.055894,1438.350208,1817.682618,1227.879113,15.795477,11.568235,...,336.446748,12.623033,2160.909333,8590.972866,3.852319,2.0,1.0,3.0,1.0,74.0
2,10017.0,0.448938,77.079529,502.416067,600.210756,1439.109101,1820.020627,1229.422522,15.807747,11.574866,...,337.082502,12.637951,2161.819062,8593.031745,3.866201,2.0,1.0,3.0,1.0,74.0
3,10024.0,0.449883,77.079529,502.469893,600.369717,1439.240230,1819.188327,1228.538726,15.816360,11.578198,...,337.162828,12.631509,2162.768666,8593.781545,3.863328,2.0,1.0,3.0,1.0,74.0
4,10031.0,0.449379,77.079529,502.401271,600.298227,1439.064004,1818.963540,1228.389046,15.807513,11.571593,...,336.966936,12.624872,2162.619544,8593.220200,3.860818,2.0,1.0,3.0,1.0,74.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263442,10036.0,0.502866,38.407928,507.301734,567.846845,1286.087972,1549.487006,1126.363646,14.314363,11.970734,...,226.607581,11.354816,1754.978021,8076.168288,2.214107,20.0,66.0,3.0,0.0,0.0
5263443,10026.0,0.502551,38.583710,507.308340,567.942650,1287.089618,1552.522723,1128.293601,14.322270,11.972770,...,227.318482,11.371490,1756.479769,8079.087036,2.226891,20.0,66.0,3.0,0.0,0.0
5263444,10020.0,0.502866,38.847378,507.361541,568.241901,1288.541567,1555.489945,1129.695621,14.341053,11.978128,...,228.302182,11.384707,1760.043718,8083.965798,2.241299,20.0,66.0,3.0,0.0,0.0
5263445,10012.0,0.502740,38.935268,507.380028,568.462600,1288.872381,1554.725363,1128.673780,14.353299,11.980930,...,228.510961,11.381855,1762.353189,8085.691199,2.240604,20.0,66.0,3.0,0.0,0.0
5263446,10002.0,0.502740,39.111050,507.415994,568.615254,1289.865798,1557.553338,1130.431629,14.364547,11.985394,...,229.208269,11.398017,1764.058505,8088.581454,2.252723,20.0,66.0,3.0,0.0,0.0

,alt,Mach,TRA,T2,T24,T30,T48,T50,P15,P2,...,P40,P50,Nf,Nc,Wf,unit,cycle,Fc,hs,RUL
0,10014.0,0.457506,77.255310,503.176696,601.369822,1441.086963,1822.407728,1230.069061,15.900837,11.636834,...,338.924861,12.659612,2165.845658,8599.379660,3.888887,11.0,1.0,3.0,1.0,58.0
1,10020.0,0.457947,77.255310,503.192949,601.381211,1441.055436,1822.376094,1230.025551,15.900690,11.637199,...,338.880009,12.656794,2165.802442,8599.261676,3.888376,11.0,1.0,3.0,1.0,58.0
2,10029.0,0.458451,77.255310,503.203187,601.392126,1441.063188,1822.350721,1229.965758,15.899810,11.636655,...,338.853562,12.653878,2165.850503,8599.291842,3.887927,11.0,1.0,3.0,1.0,58.0
3,10034.0,0.458136,77.255310,503.158580,601.348485,1440.964145,1822.141800,1229.809741,15.894349,11.632321,...,338.737926,12.649651,2165.818130,8599.008692,3.886111,11.0,1.0,3.0,1.0,58.0
4,10045.0,0.458010,77.255310,503.105629,601.285695,1440.852510,1822.019760,1229.732630,15.886351,11.626363,...,338.585509,12.644455,2165.716258,8598.651500,3.884250,11.0,1.0,3.0,1.0,58.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253738,10027.0,0.382473,25.136539,497.040848,544.098139,1203.357895,1421.337905,1077.482738,12.837452,11.143805,...,177.161207,10.930024,1545.901677,7793.390403,1.597471,15.0,67.0,2.0,0.0,0.0
1253739,10022.0,0.382158,25.136539,497.035821,544.035020,1203.472392,1422.772517,1078.697718,12.835965,11.144114,...,177.248757,10.935884,1545.145061,7793.313270,1.601279,15.0,67.0,2.0,0.0,0.0
1253740,10016.0,0.381969,25.136539,497.043961,544.055787,1203.507712,1422.445115,1078.410015,12.838463,11.145616,...,177.282416,10.937328,1545.342359,7793.574088,1.600758,15.0,67.0,2.0,0.0,0.0
1253741,10010.0,0.381717,25.136539,497.047255,544.060142,1203.529870,1422.576000,1078.539340,12.839843,11.146680,...,177.307199,10.939893,1545.300096,7793.618063,1.601250,15.0,67.0,2.0,0.0,0.0
1253742,10003.0,0.381402,25.136539,497.049793,544.066645,1203.566865,1422.622803,1078.589932,12.841603,11.147872,...,177.343813,10.942771,1545.309090,7793.743144,1.601606,15.0,67.0,2.0,0.0,0.0

### Choosing Specific Unitis for Training and Testing

In [21]:
df_Dev = df_Dev[(df_Dev['unit'] == 16) | (df_Dev['unit'] == 18) | (df_Dev['unit'] == 20)]
df_Test = df_Test[(df_Test['unit'] == 11) | (df_Test['unit'] == 14) | (df_Test['unit'] == 15)]
#df_Test = df_Test[(df_Test['unit'] == 14)]

In [22]:
print(np.shape(df_Dev))
print(np.shape(df_Test))

(2424174, 23)
(1253743, 23)

### Preprocessing

In [23]:
def preprocess_inputs(df):
    df = df.copy()  
    
    y = df[['RUL', 'unit', 'cycle']]
    X = df.drop('RUL', axis=1).copy()
    
    return X, y

In [24]:
x_train, y_train = preprocess_inputs(df_Dev)
x_test, y_test = preprocess_inputs(df_Test)

## Units and Cycle

Columns "unit" and "cycle" are not interesting for linear regression or NN.

In [25]:
x_train.drop("unit",axis=1,inplace=True)
x_test.drop("unit",axis=1,inplace=True)
#y_train.drop("unit",axis=1,inplace=True)
#y_test.drop("unit",axis=1,inplace=True)

x_train.drop("cycle",axis=1,inplace=True)
x_test.drop("cycle",axis=1,inplace=True)
#y_train.drop("cycle",axis=1,inplace=True)
#y_test.drop("cycle",axis=1,inplace=True)

x_train.drop("Fc",axis=1,inplace=True)
x_test.drop("Fc",axis=1,inplace=True)

x_train.drop("hs",axis=1,inplace=True)
x_test.drop("hs",axis=1,inplace=True)

y_train = y_train.RUL
y_test = y_test.RUL

display(x_train)
display(y_train)
display(x_test)
display(y_test)

,alt,Mach,TRA,T2,T24,T30,T48,T50,P15,P2,P21,P24,Ps30,P40,P50,Nf,Nc,Wf
2839273,10003.0,0.463176,78.222099,503.721197,602.809026,1445.734091,1831.247582,1234.668125,16.004249,11.682622,16.247968,20.434736,337.504159,342.896274,12.724826,2175.117797,8613.836569,3.953215
2839274,10012.0,0.463302,78.222099,503.699197,602.884699,1445.729730,1830.328855,1233.775609,16.004450,11.679440,16.248173,20.439561,337.426816,342.829847,12.715234,2175.909457,8614.129409,3.948704
2839275,10021.0,0.463491,78.222099,503.682048,602.850026,1445.623942,1830.356293,1233.817761,15.999599,11.676661,16.243248,20.433093,337.302302,342.701376,12.710859,2175.695109,8613.720922,3.947722
2839276,10029.0,0.463491,78.222099,503.653483,602.817989,1445.560836,1830.231656,1233.717364,15.995012,11.673181,16.238591,20.427294,337.211142,342.609169,12.707072,2175.670300,8613.535580,3.946362
2839277,10037.0,0.463743,78.222099,503.645699,602.803554,1445.513032,1830.195152,1233.683058,15.992129,11.671315,16.235664,20.423575,337.138232,342.534814,12.703789,2175.614260,8613.369578,3.945530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263442,10036.0,0.502866,38.407928,507.301734,567.846845,1286.087972,1549.487006,1126.363646,14.314363,11.970734,14.532349,16.908754,222.237320,226.607581,11.354816,1754.978021,8076.168288,2.214107
5263443,10026.0,0.502551,38.583710,507.308340,567.942650,1287.089618,1552.522723,1128.293601,14.322270,11.972770,14.540376,16.920754,222.956874,227.318482,11.371490,1756.479769,8079.087036,2.226891
5263444,10020.0,0.502866,38.847378,507.361541,568.241901,1288.541567,1555.489945,1129.695621,14.341053,11.978128,14.559445,16.951657,223.934067,228.302182,11.384707,1760.043718,8083.965798,2.241299
5263445,10012.0,0.502740,38.935268,507.380028,568.462600,1288.872381,1554.725363,1128.673780,14.353299,11.980930,14.571877,16.973923,224.122352,228.510961,11.381855,1762.353189,8085.691199,2.240604
5263446,10002.0,0.502740,39.111050,507.415994,568.615254,1289.865798,1557.553338,1130.431629,14.364547,11.985394,14.583296,16.991253,224.826670,229.208269,11.398017,1764.058505,8088.581454,2.252723

2839273    62.0
2839274    62.0
2839275    62.0
2839276    62.0
2839277    62.0
           ...
5263442     0.0
5263443     0.0
5263444     0.0
5263445     0.0
5263446     0.0
Name: RUL, Length: 2424174, dtype: float64

,alt,Mach,TRA,T2,T24,T30,T48,T50,P15,P2,P21,P24,Ps30,P40,P50,Nf,Nc,Wf
0,10014.0,0.457506,77.255310,503.176696,601.369822,1441.086963,1822.407728,1230.069061,15.900837,11.636834,16.142982,20.267629,333.560157,338.924861,12.659612,2165.845658,8599.379660,3.888887
1,10020.0,0.457947,77.255310,503.192949,601.381211,1441.055436,1822.376094,1230.025551,15.900690,11.637199,16.142833,20.267529,333.515906,338.880009,12.656794,2165.802442,8599.261676,3.888376
2,10029.0,0.458451,77.255310,503.203187,601.392126,1441.063188,1822.350721,1229.965758,15.899810,11.636655,16.141939,20.266716,333.489597,338.853562,12.653878,2165.850503,8599.291842,3.887927
3,10034.0,0.458136,77.255310,503.158580,601.348485,1440.964145,1822.141800,1229.809741,15.894349,11.632321,16.136395,20.260029,333.374654,338.737926,12.649651,2165.818130,8599.008692,3.886111
4,10045.0,0.458010,77.255310,503.105629,601.285695,1440.852510,1822.019760,1229.732630,15.886351,11.626363,16.128275,20.249683,333.225018,338.585509,12.644455,2165.716258,8598.651500,3.884250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253738,10027.0,0.382473,25.136539,497.040848,544.098139,1203.357895,1421.337905,1077.482738,12.837452,11.143805,13.032946,14.657219,173.491558,177.161207,10.930024,1545.901677,7793.390403,1.597471
1253739,10022.0,0.382158,25.136539,497.035821,544.035020,1203.472392,1422.772517,1078.697718,12.835965,11.144114,13.031436,14.652980,173.588893,177.248757,10.935884,1545.145061,7793.313270,1.601279
1253740,10016.0,0.381969,25.136539,497.043961,544.055787,1203.507712,1422.445115,1078.410015,12.838463,11.145616,13.033973,14.656059,173.618887,177.282416,10.937328,1545.342359,7793.574088,1.600758
1253741,10010.0,0.381717,25.136539,497.047255,544.060142,1203.529870,1422.576000,1078.539340,12.839843,11.146680,13.035374,14.657504,173.643837,177.307199,10.939893,1545.300096,7793.618063,1.601250
1253742,10003.0,0.381402,25.136539,497.049793,544.066645,1203.566865,1422.622803,1078.589932,12.841603,11.147872,13.037160,14.659412,173.679844,177.343813,10.942771,1545.309090,7793.743144,1.601606

0          58.0
1          58.0
2          58.0
3          58.0
4          58.0
           ...
1253738     0.0
1253739     0.0
1253740     0.0
1253741     0.0
1253742     0.0
Name: RUL, Length: 1253743, dtype: float64

### Normalization

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

#from sklearn.decomposition import PCA
# Make an instance of the Model
#pca = PCA(.98)
#pca.fit(X_train)
#X_train = pca.transform(X_train)
#X_test = pca.transform(X_test)

### Machine Learning or Deep Learning Models

In [27]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [28]:
y_pred_reg = reg.predict(x_test)

from sklearn.metrics import mean_squared_error

rmse = mean_squared_error(y_pred_reg,y_test, squared=False)
print('RMSE = ', rmse)

print('Actual RUL:')
display(pd.DataFrame(y_test, columns = ['RUL']))
print('Predicted RUL:')
display(pd.DataFrame(y_pred_reg, columns = ['RUL']))


#plt.figure(figsize=(10, 6))
#plt.title("Predicted vs. Actual :)", size=16)
#plt.scatter(range(1253743), np.squeeze(y_test))
#plt.plot(range(1253743), np.squeeze(y_pred_reg), c="red")
#plt.show()

RMSE =  10.681985546732907
Actual RUL:

          RUL
0        58.0
1        58.0
2        58.0
3        58.0
4        58.0
...       ...
1253738   0.0
1253739   0.0
1253740   0.0
1253741   0.0
1253742   0.0

[1253743 rows x 1 columns]

Predicted RUL:

               RUL
0        52.865196
1        52.788166
2        52.802933
3        52.928078
4        52.907725
...            ...
1253738  -0.064101
1253739  -1.639933
1253740  -1.098669
1253741  -1.201601
1253742  -1.196421

[1253743 rows x 1 columns]

In [29]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(32, input_dim=18, kernel_initializer='normal', activation='relu'))
model.add(tf.keras.layers.Dropout(0.12))
model.add(tf.keras.layers.Dense(32, kernel_initializer='normal', activation='relu'))
model.add(tf.keras.layers.Dense(32, kernel_initializer='normal', activation='relu'))
model.add(tf.keras.layers.Dense(1, kernel_initializer='normal', activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_squared_error'])

In [30]:
history = model.fit(
    x_train,
    y_train,
    validation_split=0.1,
    batch_size=512,
    epochs=2500,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(
            monitor='val_loss',
            patience=7,
            restore_best_weights=True
        )
    ]
)

Epoch 1/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 114.7863 - mean_squared_error: 114.7863 - val_loss: 12.1572 - val_mean_squared_error: 12.1572
Epoch 2/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 46.9825 - mean_squared_error: 46.9825 - val_loss: 16.4818 - val_mean_squared_error: 16.4818
Epoch 3/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 41.0410 - mean_squared_error: 41.0410 - val_loss: 16.7100 - val_mean_squared_error: 16.7100
Epoch 4/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 36.3457 - mean_squared_error: 36.3457 - val_loss: 18.7368 - val_mean_squared_error: 18.7368
Epoch 5/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 32.6694 - mean_squared_error: 32.6694 - val_loss: 16.8430 - val_mean_squared_error: 16.8430
Epoch 6/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 30.6301 - mean_squared_error: 30.6301 - val_loss: 17.7108 - val_mean_squared_error: 17.7108
Epoch 7/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 29.3621 - mean_squared_error: 29.3621 - val_loss: 17.3650 - val_mean_squared_error: 17.3650
Epoch 8/2500
4262/4262 [==============================] - 9s 2ms/step - loss: 27.8860 - mean_squared_error: 27.8860 - val_loss: 26.9107 - val_mean_squared_error: 26.9107

In [31]:
model.save('ANN.h5')

In [32]:
y_pred_ann = model.predict(x_test)

rmse = mean_squared_error(y_pred_ann,y_test, squared=False)
print('RMSE = ', rmse)

RMSE =  7.839693605771822